"""Shared domain contracts and pure logic for all LLM Wiki runtimes."""

from .chunking import Chunk, chunk_pages, chunk_text
from .documents import (
    DocumentIdentity,
    DocumentKind,
    DocumentStatus,
    InvalidStatusTransition,
    assert_status_transition,
    join_logical_path,
    normalize_directory_path,
)
from .evaluation import (
    EVALUATION_SCHEMA_VERSION,
    EvalCase,
    EvaluationReport,
    EvaluationRun,
    PromotionDecision,
    RankedResult,
    RelevanceJudgment,
    evaluate_rankings,
    evaluation_dataset_digest,
    load_cases,
    promotion_decision,
)
from .facets import FACET_KEYS, UnknownFacetError, apply_rollup, rollup_from_metas, validate_facets
from .models import (
    EmbeddingClient,
    EmbeddingError,
    EmbeddingInputError,
    EmbeddingProfile,
    EmbeddingUnavailable,
    InvalidEmbeddingResponse,
)
from .rag import (
    RAG_ERROR_CONTRACTS,
    RagBudget,
    RagCitation,
    RagCompletionReason,
    RagDomainError,
    RagErrorContract,
    RagPageState,
    RagRunConfig,
    RagStepStatus,
    RagStepType,
    RagUsage,
    RagWorkItem,
    new_rag_error,
    remaining_work_items,
    validate_worklist,
)
from .references import build_lookup_maps, extract_references, parse_citation_filename, parse_wiki_links
from .search import (
    ContextExpander,
    HybridRetrievalService,
    Reranker,
    Retriever,
    RetrieverUnavailable,
    SearchArea,
    SearchHit,
    SearchQuery,
    SearchResult,
    SearchScope,
)
from .signals import sanitized_boundary_signal_or_unknown
from .wiki import DuplicateDocumentError, VersionConflict, WikiWriteBundle

__version__ = "0.1.0"

__all__ = [
    "Chunk",
    "ContextExpander",
    "DocumentIdentity",
    "DocumentKind",
    "DocumentStatus",
    "DuplicateDocumentError",
    "EVALUATION_SCHEMA_VERSION",
    "EvalCase",
    "EmbeddingClient",
    "EmbeddingError",
    "EmbeddingInputError",
    "EmbeddingProfile",
    "EmbeddingUnavailable",
    "EvaluationReport",
    "EvaluationRun",
    "FACET_KEYS",
    "HybridRetrievalService",
    "InvalidStatusTransition",
    "InvalidEmbeddingResponse",
    "PromotionDecision",
    "RAG_ERROR_CONTRACTS",
    "RagBudget",
    "RagCitation",
    "RagCompletionReason",
    "RagDomainError",
    "RagErrorContract",
    "RagPageState",
    "RagRunConfig",
    "RagStepStatus",
    "RagStepType",
    "RagUsage",
    "RagWorkItem",
    "RankedResult",
    "RelevanceJudgment",
    "assert_status_transition",
    "chunk_pages",
    "chunk_text",
    "join_logical_path",
    "normalize_directory_path",
    "new_rag_error",
    "Reranker",
    "Retriever",
    "RetrieverUnavailable",
    "SearchArea",
    "SearchHit",
    "SearchQuery",
    "SearchResult",
    "SearchScope",
    "UnknownFacetError",
    "VersionConflict",
    "WikiWriteBundle",
    "apply_rollup",
    "build_lookup_maps",
    "extract_references",
    "evaluation_dataset_digest",
    "evaluate_rankings",
    "load_cases",
    "parse_citation_filename",
    "parse_wiki_links",
    "promotion_decision",
    "remaining_work_items",
    "rollup_from_metas",
    "sanitized_boundary_signal_or_unknown",
    "validate_facets",
    "validate_worklist",
]
